env:
  matrix:
  - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
addons:
  firefox: latest
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9
language: node_js
os:
- linux
- osx
services:
- xvfb
sudo: false
install:
- npm install
script:
- node -v
# - npm run test:CI
before_script:
- export DISPLAY=:99.0
before_install:
- npm --version
- npm config set spin false
- npm install -g grunt-cli
- npm install -g node-gyp
- npm install -g ember-cli
before_deploy: # Prepare OSX to pack binaries, and Linux to publish webpage to Surge.
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install curl                                  ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd $TRAVIS_BUILD_DIR && travis/download-homebrew   ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install makensis fakeroot dpkg                ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/cask-versions/wine-devel     ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then VERSION=$(sh scripts/obtenerVersion.sh)            ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then VERSION_DEB=$(echo ${VERSION} | sed -e
  's/-/~/g')  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then NOMBRE=$(sh scripts/obtenerNombre.sh)              ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "Detectando version $VERSION para
  compilar"   ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 120 make empaquetar                    ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ember build --environment=development            ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm install -g surge                             ;
  fi
deploy:
  - provider: releases # When there is a tag, pack the installers and upload to Github.
    skip_cleanup: true
    prerelease: true
    api_key:
      secure: 1ShkmF5gvpFKzCeGCPqzFl1Lm2Ox6fh0oxDWMaGKBSQW6sgeEY6TIhbYcSh4cqOSrBxazMNC4/JZ4F/I6p4fdyxESNN+aioJR02kbHRUHDC7OUPt3YfqYTQt2yAp31YItEeiwac2F7y4y54u1lAN1Ig0nKaGglKWOORhW7olsX1ZoPItkXPGvwpw8e1VKrR/F/zRhk/OYkoV7Ix/x3Zr5y1i0E25RCQa7U88Ov3h0ErkgfFtmzcI2I9ZZSw7S5ZQi7LyLYUx+29uIHvZb2h7LkZTqJOhfGqn1wgp3FSmRADxD9Gpmm56Ol+OZ9EML9SuWmtKVMPnp7xWnp+fafvrwcROdTHacFHCJNi9HUz7qMb9hHLgLFVOSso8DHrb41Em4r49AkaZC5MPe0VnrVRyuV/Neo/xBhjt0RYSBWViUVKx4O3wH0EhspkZBcpBwnKbhQ9qXB2cgbqnmreDdSyyU5exy/2i7OhNm2WGZK71eMosVdLu6RBiDmHws8jUSDIBmpo/RNSO+G8G7RaSz3+Zo20xpMDlnu+7lr/DiV8Su7186f2O7VIOpvpla3GQDRwJf2rllJn6CkGGrb4+b/N+azWs2meuzFrY/cA06IHztKMIlBF1jOawCTU2Ladc4GwbeREFHKe4J7Zt1lyCTRBl4DjjE0CvgeHFLWiDGzyZ6Uw=
    file:
    - binarios/${NOMBRE}-${VERSION}.dmg
    - binarios/${NOMBRE}-${VERSION}.exe
    - binarios/${NOMBRE}-${VERSION}-linux-x64.zip
    - binarios/${NOMBRE}-${VERSION}-linux-ia32.zip
    - binarios/${NOMBRE}_${VERSION_DEB}_amd64.deb
    on:
      tags: true
      all_branches: true
      condition: "$TRAVIS_OS_NAME == osx"
  - provider: surge # Whenever master gets updated, update master site.
    project: ./dist/
    domain: master-pilas-bloques.surge.sh
    skip_cleanup: true
    on:
      branch: master
      condition: "$TRAVIS_OS_NAME == linux"
  - provider: surge # Whenever develop gets updated, update develop site.
    project: ./dist/
    domain: develop-pilas-bloques.surge.sh
    skip_cleanup: true
    on:
      branch: develop
      condition: "$TRAVIS_OS_NAME == linux"